name: Terraform_Practice

on:
  workflow_dispatch:
  
jobs:
  my_job:
    name: Terraform_Practice
    runs-on: ubuntu-22.04
     
    steps:
      - name: Login to Azure
        uses: hyperskill/azure-login@v3.0.0
        with:
          client_id: be7d4a8e-82c8-40f3-badc-f84c5d233490
          client_secret: hOt8Q~weoqgDpDUlQiRjYIQKid6i5P5djKQgccy8
          subscription_id: 268d57ac-35fd-49c6-b7a9-c0ce9f4c221a
          tenant_id: 8118274f-b824-4932-8388-e1042bb85265 
             
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -no-color

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
        
        # "input=false" prevents Terraform from waiting for interactive input.
        # "no-color" makes GitHub Actions logs cleaner and easier to read.
        # "auto-approve" auto-approves terraform apply		
